#cloud-config

# Update and upgrade packages
package_update: true
package_upgrade: true

# Install packages
packages:
  - curl
  - wget
  - git
  - unzip
  - htop
  - tree
  - jq
  - vim
  - python3-pip
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - nginx

# Create directories
runcmd:
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io

  # Add user to docker group
  - usermod -aG docker azureuser

  # Install Docker Compose
  - curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

  # Install Azure CLI
  - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

  # Install Node.js
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs

  # Create application directory
  - mkdir -p /opt/devops-app
  - chown -R azureuser:azureuser /opt/devops-app

  # Start and enable services
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable nginx
  - systemctl start nginx

# Write files
write_files:
  - path: /var/www/html/health.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Azure Server Health Check</title>
      </head>
      <body>
          <h1>Azure Server is Running</h1>
          <p>Timestamp: <script>document.write(new Date().toISOString());</script></p>
          <p>VM Name: <script>
              fetch('/metadata/instance/compute/name?api-version=2021-02-01&format=text', {
                  headers: {'Metadata': 'true'}
              }).then(r => r.text()).then(name => document.write(name));
          </script></p>
      </body>
      </html>
    permissions: '0644'
    owner: root:root

  - path: /opt/devops-app/azure-init.log
    content: |
      Azure VM initialization completed at $(date)
      VM Size: Standard_B1s
      Location: East US
      Admin User: azureuser
    permissions: '0644'
    owner: azureuser:azureuser

# Final commands
final_message: "Azure VM setup completed successfully!"

# Logging
output:
  init: "/var/log/cloud-init.log"
  config: "/var/log/cloud-init-config.log"
  final: "/var/log/cloud-init-final.log"