global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ '44.237.126.178:9100' ]

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ '44.237.126.178:8080' ]

  - job_name: 'devops-app'
    metrics_path: /metrics
    static_configs:
      # The app is running on the host, exposed on port 80
      - targets: [ '44.237.126.178:80' ]