---
- name: Configure Web Server VM
  hosts: all
  become: yes  # This tells Ansible to use 'sudo' for all tasks

  vars:
    devops_group: devops

  tasks:
    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Only update once per hour
      changed_when: false # This task should not report a change

    - name: Create the 'devops' group
      group:
        name: "{{ devops_group }}"
        state: present

    - name: Ensure the /opt directory exists
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Copy sample config file with specific permissions
      copy:
        src: files/config.txt
        dest: /opt/config.txt
        owner: root
        group: "{{ devops_group }}"
        mode: '0660' # rw- for owner (root), rw- for group (devops), --- for others
      notify: Reload Nginx # Example of using a handler

    # --- PostgreSQL Installation ---
    - name: Install PostgreSQL and its dependencies
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: latest # Ensures the latest version is installed

    - name: Ensure PostgreSQL service is enabled and running
      systemd:
        name: postgresql
        state: started
        enabled: yes # Starts on boot

    # --- Web Server (Nginx) Installation ---
    - name: Install Nginx web server
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is enabled and running
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Verify Nginx is accessible
      uri:
        url: http://localhost
        status_code: 200
      run_once: true # This check only runs on one host

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded